export const mockTeachers = [
  {
    _id: 1,
    course_name: "Mathematics 101",
    creator_id: 1,
    uuid: 1,
    name: "Juan Perex",
    permissions: {
      ModulesAndResources: true,
      Exams: true,
      Tasks: false,
      Feedbacks: false,
    },
  },
  {
    _id: 1,
    course_name: "Mathematics 101",
    creator_id: 1,
    uuid: 6,
    name: "Juana Azurduy",
    permissions: {
      ModulesAndResources: true,
      Exams: true,
      Tasks: false,
      Feedbacks: true,
    },
  },
  {
    _id: 1,
    course_name: "Mathematics 101",
    creator_id: 1,
    uuid: 7,
    name: "Alfonso Quispe",
    permissions: {
      ModulesAndResources: true,
      Exams: false,
      Tasks: false,
      Feedbacks: false,
    },
  },
  {
    _id: 2,
    course_name: "Physics 201",
    creator_id: 200,
    uuid: 2,
    name: "Maria Gonzalez",
    permissions: {
      ModulesAndResources: true,
      Exams: false,
      Tasks: true,
      Feedbacks: true,
    },
  },
  {
    _id: 3,
    course_name: "History 101",
    creator_id: 450,
    uuid: 3,
    name: "Carlos Ramirez",
    permissions: {
      ModulesAndResources: false,
      Exams: true,
      Tasks: true,
      Feedbacks: false,
    },
  },
  {
    _id: 3,
    course_name: "History 101",
    creator_id: 450,
    uuid: 80,
    name: "Jujuuuuy",
    permissions: {
      ModulesAndResources: false,
      Exams: false,
      Tasks: true,
      Feedbacks: false,
    },
  },
  {
    _id: 4,
    course_name: "Chemistry 301",
    creator_id: 10,
    uuid: 4,
    name: "Ana Lopez",
    permissions: {
      ModulesAndResources: true,
      Exams: true,
      Tasks: true,
      Feedbacks: true,
    },
  },
  {
    _id: 5,
    course_name: "Biology 101",
    creator_id: 2,
    uuid: 5,
    name: "Luis Fernandez",
    permissions: {
      ModulesAndResources: false,
      Exams: false,
      Tasks: true,
      Feedbacks: true,
    },
  },
];
